### ISSUE TITLE
Import over path?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [pikapkg/cdn#9] opened 2020-05-25 07:18 UTC
For example, `rxjs` main export are like this:

```
import { range } from "rxjs";
// Turns into
import { range } from "https://cdn.pika.dev/rxjs@^6.5.5";
```

But RxJS operators are under `rxjs/operators`. How can I import these files?

**Comment by FredKSchott** [comment] 2020-06-14 22:16
Duplicate of https://github.com/pikapkg/cdn/issues/14, support is coming soon

**Closed by FredKSchott** 2020-06-14 22:16 UTC
