### ISSUE TITLE
Pinned URLs don't support the `?dts` query parameter

### ISSUE THREAD

**Issue by kitsonk** [pikapkg/cdn#251] opened 2021-12-23 04:43 UTC
We in Deno are working on providing a "quick fix" in the language server to convert an unpinned URL to a pinned URL with Skypack, so people can quickly convert their code to "fixed" pinned versions.  The challenge is that the pinned URLs do not provide the `x-typescript-types` headers when a query parameter is changed, meaning that anyone converting to a pinned URL would "lose" their type definitions.  For example:

```
> curl -I https://cdn.skypack.dev/preact?dts
HTTP/2 200 
date: Thu, 23 Dec 2021 04:34:58 GMT
content-type: application/javascript; charset=utf-8
content-length: 772
access-control-allow-origin: *
x-typescript-types: /-/preact@v10.6.4-S6FVYh0uu9lnoPz06OtD/dist=es2019,mode=types/src/index.d.ts
cache-control: public, max-age=300
access-control-expose-headers: X-Import-Status, X-Import-Url, X-Pinned-Url, X-TypeScript-Types, Content-Length
x-import-status: SUCCESS
x-pinned-url: /pin/preact@v10.6.4-S6FVYh0uu9lnoPz06OtD/mode=imports/optimized/preact.js
x-import-url: /-/preact@v10.6.4-S6FVYh0uu9lnoPz06OtD/dist=es2019,mode=imports/optimized/preact.js
```

And then:

```
> curl -I https://cdn.skypack.dev/pin/preact@v10.6.4-S6FVYh0uu9lnoPz06OtD/mode=imports/optimized/preact.js?dts
HTTP/2 200 
date: Thu, 23 Dec 2021 04:35:32 GMT
content-type: application/javascript; charset=utf-8
content-length: 468
access-control-allow-origin: *
cache-control: private, max-age=31536000
x-import-url: /-/preact@v10.6.4-S6FVYh0uu9lnoPz06OtD/dist=es2020,mode=imports/optimized/preact.js
```

**Comment by jsejcksn** [comment] 2022-02-08 23:25
Duplicate of https://github.com/skypackjs/skypack-cdn/issues/245

**Closed as not planned** 2024-04-24 09:07 UTC
