### ISSUE TITLE
Support JSON imports

### ISSUE THREAD

**Issue by haylinmoore** [pikapkg/cdn#57] opened 2020-10-01 14:11 UTC
When I try to import the npm module using `import cheerio from "https://cdn.skypack.dev/cheerio?dts";` I get the error 

```
deno run --lock=lock.json --lock-write --allow-all index.ts
Download https://cdn.skypack.dev/new/htmlparser2@v3.10.1/dist=es2020?from=cheerio
Download https://cdn.skypack.dev/new/dom-serializer@v0.1.1/dist=es2020?from=cheerio
Download https://cdn.skypack.dev/new/css-select@v1.2.0/dist=es2020?from=cheerio
Download https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json
error: Import 'https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json' failed: 404 Not Found
```

This appears to be skypack imports being wrong

**Comment by haylinmoore** [comment] 2020-10-01 14:15
After more testing the same thing happens with the react package

**Comment by ghost** [comment] 2020-10-02 23:47
> When I try to import the npm module using `import cheerio from "https://cdn.skypack.dev/cheerio?dts";` I get the error
> 
> ```
> deno run --lock=lock.json --lock-write --allow-all index.ts
> Download https://cdn.skypack.dev/new/htmlparser2@v3.10.1/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/new/dom-serializer@v0.1.1/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/new/css-select@v1.2.0/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json
> error: Import 'https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json' failed: 404 Not Found
> ```
> 
> This appears to be skypack imports being wrong

**Comment by ghost** [comment] 2020-10-02 23:48
https://github.com/pikapkg/skypack-cdn/issues/57#issuecomment-703003875

**Comment by coryrylan** [comment] 2020-10-09 18:00
Getting similar issues with our packages as well, 404s on most of them it looks like

https://codepen.io/coryrylan/pen/oNxvgvG

**Comment by loucyx** [comment] 2020-10-24 02:18
I think I'm having the same issue. So when I write something like this:
```typescript
// test.ts
import { isObject } from "https://cdn.skypack.dev/@vangware/utils?dts";

console.log(isObject({}) ? "is object" : "isn't an object");
```
And then I run:
```
deno run ./test.ts
```
I get a list of the downloads, but all the URLs are missing the `.d.ts` extension:
```
...
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/ArrayOrIterable
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/DecimalTuple
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entries
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entry
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Falsy
Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Filterer
...
```
I think this problems is related to [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) in TypeScript, and the way Skypack parses that.

**Comment by drwpow** [comment] 2020-11-04 19:43
> When I try to import the npm module using `import cheerio from "https://cdn.skypack.dev/cheerio?dts";` I get the error
> 
> ```
> deno run --lock=lock.json --lock-write --allow-all index.ts
> Download https://cdn.skypack.dev/new/htmlparser2@v3.10.1/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/new/dom-serializer@v0.1.1/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/new/css-select@v1.2.0/dist=es2020?from=cheerio
> Download https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json
> error: Import 'https://cdn.skypack.dev/-/entities@v1.1.2-AmSiUIHF7bnhFjnIEedw/dist=es2020,mode=raw/lib/maps/decode.json' failed: 404 Not Found
> ```
> 
> This appears to be skypack imports being wrong

I’ve changed the title of the original issue to “support JSON imports“ because I believe that‘s the heart of this issue. I‘m still seeing the same error. Hope that’s OK.

**Comment by drwpow** [comment] 2020-11-04 19:44
> Getting similar issues with our packages as well, 404s on most of them it looks like
> 
> https://codepen.io/coryrylan/pen/oNxvgvG

This seems to be working for me? I see errors but I don‘t notice any coming from Skypack specifically. I‘m not sure if this relates to the original issue.

**Comment by drwpow** [comment] 2020-11-04 19:45
> I think I'm having the same issue. So when I write something like this:
> 
> ```ts
> // test.ts
> import { isObject } from "https://cdn.skypack.dev/@vangware/utils?dts";
> 
> console.log(isObject({}) ? "is object" : "isn't an object");
> ```
> 
> And then I run:
> 
> ```
> deno run ./test.ts
> ```
> 
> I get a list of the downloads, but all the URLs are missing the `.d.ts` extension:
> 
> ```
> ...
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/ArrayOrIterable
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/DecimalTuple
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entries
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entry
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Falsy
> Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Filterer
> ...
> ```
> 
> I think this problems is related to [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) in TypeScript, and the way Skypack parses that.

In Deno, try removing the `?dts` and it should work! I’m able to load that code in Deno using the latest Skypack CDN.

**Comment by loucyx** [comment] 2020-11-04 22:19
> > I think I'm having the same issue. So when I write something like this:
> > ```ts
> > // test.ts
> > import { isObject } from "https://cdn.skypack.dev/@vangware/utils?dts";
> > 
> > console.log(isObject({}) ? "is object" : "isn't an object");
> > ```
> > 
> > 
> > And then I run:
> > ```
> > deno run ./test.ts
> > ```
> > 
> > 
> > I get a list of the downloads, but all the URLs are missing the `.d.ts` extension:
> > ```
> > ...
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/ArrayOrIterable
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/DecimalTuple
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entries
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Entry
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Falsy
> > Download https://cdn.skypack.dev/-/@vangware/utils@v5.0.7-TyxN3ZbnewiTGIhqjMIP/dist=es2020,mode=types/esm/types/Filterer
> > ...
> > ```
> > 
> > 
> > I think this problems is related to [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) in TypeScript, and the way Skypack parses that.
> 
> In Deno, try removing the `?dts` and it should work! I’m able to load that code in Deno using the latest Skypack CDN.

I might be wrong, but as far as I know without `?dts` skypack only serves the js files, which "work" but without typecheck. Still the issue is that skypack should serve those files with the `.d.ts` extension and the extension is missing. I think [type-only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) are not being parsed correctly. I'll check if I have typecheck without `?dts` and come back to this thread if it works.

Edit: I just checked, without `?dts` I don't get any type check...

**Comment by FredKSchott** [comment] 2020-11-17 07:27
This is a bit of a hodgepodge of different issues, but I believe each has been fixed as much as possible:

- cheerio - has Node.js dependencies, can't be loaded in Deno
- "@vangware/utils?dts" - fixed on our end, but seems to be a Deno issue blocking this now: `error: Expected Comma, got Some(Colon) at https://cdn.skypack.dev/-/@vangware/utils@v5.0.8-CtBKSf8HoygVSO2iStQb/dist=es2020,mode=types/esm/types/DecimalTuple.d.ts:5:15`
- the codepen linked above: works!

If you run into a different issue, please file a new issue in GH!

**Closed as completed by FredKSchott** 2020-11-17 07:27 UTC
Labels: enhancement
