### ISSUE TITLE
missing x-typescript-types header for https://cdn.skypack.dev/rxjs@6.6.3/webSocket?dts

### ISSUE THREAD

**Issue by marcushultman** [pikapkg/cdn#60] opened 2020-10-15 10:13 UTC
```
$ curl -I "https://cdn.skypack.dev/rxjs@6.6.3/webSocket?dts"
HTTP/2 200
date: Thu, 15 Oct 2020 10:09:57 GMT
content-type: application/javascript; charset=utf-8
content-length: 0
set-cookie: __cfduid=d30cf0287b513e49dadd5e0dd65dc8e961602756597; expires=Sat, 14-Nov-20 10:09:57 GMT; path=/; domain=.skypack.dev; HttpOnly; SameSite=Lax
access-control-allow-origin: *
x-import-url: /-/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/dist=es2020/rxjs/webSocket.js
cache-control: private, max-age=300
x-pinned-url: /pin/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/rxjs/webSocket.js
etag: W/"2b3-euEPbHWgq0f2J5W/hoXfPuCjDf8"
x-import-status: SUCCESS
x-vercel-cache: MISS
age: 0
x-vercel-id: arn1::sfo1::rvvvd-1602756597589-91eaf039ea8d
strict-transport-security: max-age=63072000
cf-cache-status: DYNAMIC
cf-request-id: 05cd55ef3e0000d891cf91c000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=65&lkg-time=1602756598"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5e28bf5ec8b7d891-CPH
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```
```
$ curl -I "https://cdn.skypack.dev/rxjs@6.6.3?dts"
HTTP/2 200
date: Thu, 15 Oct 2020 10:10:02 GMT
content-type: application/javascript; charset=utf-8
content-length: 0
set-cookie: __cfduid=d9ad6fae2d91613ebc931403799daaebc1602756602; expires=Sat, 14-Nov-20 10:10:02 GMT; path=/; domain=.skypack.dev; HttpOnly; SameSite=Lax
access-control-allow-origin: *
x-import-url: /-/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/dist=es2020/rxjs.js
cache-control: private, max-age=300
x-pinned-url: /pin/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/rxjs.js
x-import-status: SUCCESS
etag: W/"28b-6WPTbxGjF8rocKfAhBnaSXD5l+k"
x-typescript-types: /-/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/dist=es2020,mode=types/index.d.ts
x-vercel-cache: MISS
age: 0
x-vercel-id: arn1::sfo1::xkms7-1602756602389-f0d52fabb650
strict-transport-security: max-age=63072000
cf-cache-status: DYNAMIC
cf-request-id: 05cd56020700001d22fc8b9000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?lkg-colo=65&lkg-time=1602756603"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5e28bf7cddb21d22-CPH
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by drwpow** [comment] 2020-10-30 23:21
Strange! I see `/rxjs?dts` is returning that types header, but not the `/rxjs/webWorker?dts` subresource as you say. Investigating this now.

**Comment by drwpow** [comment] 2020-10-30 23:30
Update: it seems that this is intended behavior; we specifically don’t return types for subresources like this. Fred is out for today; I’ll check in with him when he’s back to get the reason why this was added. And we’ll either reassess and change this behavior, or [update the docs](https://docs.skypack.dev/skypack-cdn/lookup-urls/lookup-urls#typescript-declarations) with an explanation why. Thanks for your patience.

**Comment by marcushultman** [comment] 2020-10-30 23:59
@drwpow Ok, it would at least be great if there was a way to opt in. Without the proper declarations, my application doesn't compile. I can work around the issue by overriding the types by using a direct url `https://cdn.skypack.dev/-/rxjs@v6.6.3-c2iRuUGSgpzW7rJtDXPN/dist=es2020,mode=types/webSocket/index.d.ts`, but that is not sufficient in the long run. Thanks  for looking in to it!

**Comment by FredKSchott** [comment] 2020-11-13 01:17
Appreciate your patience! I was able to look into this more: this is mainly legacy behavior back when we thought we could bundle DTS files. Today, we serve DTS files individually, which means that we actually can support this with the `?dts` flag. 

The only complexity will be in resolving `rxjs/webSocket` to it's proper type file. Is it `webSocket.d.ts` or `webSocket/index.d.ts`? Will add some handling for this kind of "lazy lookup" via redirect.

**Comment by marcushultman** [comment] 2020-11-13 09:05
@FredKSchott I would think that if the url ends with a `submodule.js?dts`, then you would look for `submodule.d.ts`, but if it ends with `submodule?dts` you'd look for `submodule/index.d.ts`. But I'm not entirely sure. In the case of `rxjs/webSocket`,  `webSocket.d.ts` will 301 redirect to the correct file `webSocket/index.d.ts `, so it doesn't really matter. Not sure if this is universally applicable.

**Comment by FredKSchott** [comment] 2020-11-17 07:00
Fixed!

**Closed as completed by FredKSchott** 2020-11-17 07:00 UTC
Labels: bug, package issue
