### ISSUE TITLE
parjs broken on deno using skypack

### ISSUE THREAD

**Issue by Dreamacro** [pikapkg/cdn#119] opened 2021-01-31 06:46 UTC
PoC

```typescript

import {float, string, whitespace} from "https://cdn.skypack.dev/parjs?dts";
import {between, manySepBy} from "https://cdn.skypack.dev/parjs/combinators?dts"

// Built-in building block parser for floating-point numbers.
const tupleElement = float();

// Allow whitespace around elements:
const paddedElement = tupleElement.pipe(
    between(whitespace())
);

// Multiple instances of {paddedElement}, separated by a comma:
const separated = paddedElement.pipe(
    manySepBy(",")
);

// Surround everything with parentheses:
const surrounded = separated.pipe(
    between("(", ")")
);

// Prints [1, 2, 3]:
console.log(surrounded.parse("(1,  2 , 3 )"));
```

errors
```
Download https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/.d.ts
Download https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/...d.ts
Check file:///Users/Dreamacro/Dev/projects/orbit/parser.ts
error: TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'ParjsCombinator'.
import { ParjsCombinator } from "../...d.ts";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/combinators/or.d.ts:5:10

TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'ParjsCombinator'.
import { ParjsCombinator } from "../../.d.ts";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/combinators/backtrack.d.ts:5:10

TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'ParjsCombinator'.
import { ParjsCombinator } from "../../.d.ts";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/combinators/must.d.ts:6:10

TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'ParjsCombinator'.
import { ParjsCombinator } from "../../.d.ts";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/combinators/not.d.ts:5:10

TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'ParjsCombinator'.
import { ParjsCombinator } from "../../.d.ts";
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/parjs@v0.12.7-G93ji3BUVH1413mAilrm/dist=es2020,mode=types/internal/combinators/recover.d.ts:7:10
Found 5 errors.
```

**Comment by drwpow** [comment] 2021-02-01 18:25
Thank you for filing! This is possibly a duplicate of #42. We are actively working to improve `?dts` support.

**Closed as completed** 2023-12-19 05:48 UTC
Labels: deno
