### ISSUE TITLE
[Package Issue] react-bootstrap

### ISSUE THREAD

**Issue by soegaard** [pikapkg/cdn#37] opened 2020-08-09 12:00 UTC
Something goes wrong, when I import react-bootstrap.

![image](https://user-images.githubusercontent.com/461765/89731588-83aee880-da48-11ea-9b42-36855d414762.png)

![image](https://user-images.githubusercontent.com/461765/89731596-91646e00-da48-11ea-9bcc-65abbe44c4a2.png)

**Comment by soegaard** [comment] 2020-08-09 17:20
A CodePen that demonstrates the problem:

https://codepen.io/soegaard/pen/NWNqggd?editors=1111

**Comment by soegaard** [comment] 2020-08-10 10:26
Search works again so I found that clicking "Run Code" on:

     https://www.skypack.dev/npm/react-bootstrap

leads to the same problem.

![image](https://user-images.githubusercontent.com/461765/89773654-a3a3e200-db04-11ea-841e-928563920630.png)

**Comment by FredKSchott** [comment] 2020-08-12 04:43
Thanks for filing! It looks like the issue is within "react-transition-group", where each of these imports is actually a package.json with a "module" entrypoint. We handle most of these, but this package uses parent directory references ("../") which confuses our resolver.

Will get a fix out for this soon

**Comment by soegaard** [comment] 2020-08-30 11:15
Any news?

**Comment by FredKSchott** [comment] 2020-08-31 02:18
@drwpow was working on this, but we had to put it on hold. Would love to get to this this week if we can

**Comment by drwpow** [comment] 2020-09-02 16:25
So good news and bad news. The good news is we fixed this problem! 🎉 But bad news: there’s an error in a subdependency so you still can’t quite load `react-bootstrap` yet.

A deep import for a subdependency of `react-bootstrap` loads a Node built-in (`process`). We _do_ polyfill the Node built-ins that are browser-friendly, but only for the default import, not deep imports (“raw” mode, or individually-loaded files). I’m going to spin up another issue for that, but keep this one open.

**Comment by soegaard** [comment] 2020-09-02 20:16
Thanks for the update. It mostly feels like good news :-)

In the case of `react-bootstrap` I don't think it will use `process` when run,
so a do-nothing stub would probably work.

But since you are looking for a general solution that applies to other packages
as well, I can see the problem isn't straightforward at all.

**Comment by drwpow** [comment] 2020-10-01 00:30
Minor update: we’ve further improved handling of packages (and CSS exports), so your experience with this package should be improved! But the un-polyfilled `process` seems is currently still happening in a deep import (`react-transition-group`). So I can’t _quite_ call this marked off, but as you stated, simply stubbing that out should do the trick for now 🙂

**Comment by drwpow** [comment] 2020-10-01 00:31
Actually, I’m going to close this issue and open one for `react-transition-group` so the tracking is easier.

**Closed as completed by drwpow** 2020-10-01 00:31 UTC
Labels: package issue
